package com.messaging.broker.registry;

import com.messaging.common.model.TopologyResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Properties;

/**
 * Stores topology information in a properties file
 */
public class TopologyPropertiesStore {
    private static final Logger log = LoggerFactory.getLogger(TopologyPropertiesStore.class);
    
    private final Path propertiesFile;

    public TopologyPropertiesStore(Path dataDir) {
        this.propertiesFile = dataDir.resolve("topology.properties");
        log.info("TopologyPropertiesStore initialized: {}", propertiesFile);
    }

    /**
     * Save current topology information
     */
    public void saveTopology(TopologyResponse topology) {
        Properties props = new Properties();
        
        props.setProperty("nodeId", topology.getNodeId());
        props.setProperty("role", topology.getRole().name());
        props.setProperty("topologyVersion", topology.getTopologyVersion() != null ? topology.getTopologyVersion() : "1.0");
        props.setProperty("lastUpdated", Instant.now().toString());
        
        // Save parent URLs
        if (topology.getRequestToFollow() != null && !topology.getRequestToFollow().isEmpty()) {
            props.setProperty("parentUrl", topology.getRequestToFollow().get(0));
            for (int i = 0; i < topology.getRequestToFollow().size(); i++) {
                props.setProperty("parentUrl." + i, topology.getRequestToFollow().get(i));
            }
        }
        
        // Save Cloud URL if applicable
        if (topology.getCloudDataUrl() != null) {
            props.setProperty("cloudDataUrl", topology.getCloudDataUrl());
        }
        if (topology.getCloudDataUrlFallback() != null) {
            props.setProperty("cloudDataUrlFallback", topology.getCloudDataUrlFallback());
        }
        
        // Save topics
        if (topology.getTopics() != null) {
            props.setProperty("topics", String.join(",", topology.getTopics()));
        }
        
        // Write to file
        try (FileWriter writer = new FileWriter(propertiesFile.toFile())) {
            props.store(writer, "Topology Information - Auto-generated by TopologyManager");
            log.info("Saved topology to file: role={}, parent={}", 
                    topology.getRole(), 
                    topology.getRequestToFollow() != null && !topology.getRequestToFollow().isEmpty() 
                        ? topology.getRequestToFollow().get(0) 
                        : "none");
        } catch (IOException e) {
            log.error("Failed to save topology properties", e);
            throw new RuntimeException("Failed to save topology properties", e);
        }
    }

    /**
     * Load topology information from file
     */
    public Properties loadTopology() {
        if (!Files.exists(propertiesFile)) {
            log.info("No existing topology file found");
            return null;
        }
        
        Properties props = new Properties();
        try (FileReader reader = new FileReader(propertiesFile.toFile())) {
            props.load(reader);
            log.info("Loaded topology from file: role={}, parent={}", 
                    props.getProperty("role"), 
                    props.getProperty("parentUrl"));
            return props;
        } catch (IOException e) {
            log.error("Failed to load topology properties", e);
            return null;
        }
    }

    /**
     * Get current parent URL from saved topology
     */
    public String getCurrentParentUrl() {
        Properties props = loadTopology();
        return props != null ? props.getProperty("parentUrl") : null;
    }

    /**
     * Get current role from saved topology
     */
    public String getCurrentRole() {
        Properties props = loadTopology();
        return props != null ? props.getProperty("role") : null;
    }
}
